### ISSUE TITLE
dm-devise not overriding devise user lookup.

### ISSUE THREAD

**Issue by postmodern** [jm81/dm-devise#10]
`current_user` ends up trying to call ActiveRecord finders from within Devise, even though dm-devise is loaded.

<pre>
wrong number of arguments (2 for 0..1)

devise (1.1.8) lib/devise/rails/warden_compat.rb:30:in `find'
devise (1.1.8) lib/devise/rails/warden_compat.rb:30:in `deserialize'
warden (1.0.3) lib/warden/session_serializer.rb:31:in `fetch'
warden (1.0.3) lib/warden/proxy.rb:182:in `user'
warden (1.0.3) lib/warden/proxy.rb:270:in `_perform_authentication'
warden (1.0.3) lib/warden/proxy.rb:90:in `authenticate'
warden (1.0.3) lib/warden/proxy.rb:100:in `authenticate?'
devise (1.1.8) lib/devise/controllers/helpers.rb:222:in `user_signed_in?'
</pre>

<pre>
class Warden::SessionSerializer
  def serialize(record)
    [record.class.name, record.id]
  end

  def deserialize(keys)
    klass, id = keys

    if klass.is_a?(Class)
      raise "Devise changed how it stores objects in session. If you are seeing this message, " <<
        "you can fix it by changing one character in your cookie secret, forcing all previous " <<
        "cookies to expire, or cleaning up your database sessions if you are using a db store."
    end

    klass.constantize.find(:first, :conditions => { :id => id })  # <------------ WTF
  rescue NameError => e
    if e.message =~ /uninitialized constant/
      Rails.logger.debug "Trying to deserialize invalid class #{klass}"
      nil
    else
      raise
    end
  end
end
</pre>

**Comment by postmodern** [comment]
Nevermind, you already fixed this in devise edge. :)
